### PR TITLE
fixes #102

### LINKED ISSUE #102: Minimum PHP version option not working
To re-produce this error, check latest version of my theme at https://themes.trac.wordpress.org/ticket/63695. Set minimum php version to 5.4 and run the plugin sniffer. It will still show all errors related to keywords or syntax available in PHP 5.4.

### PR DESCRIPTION
**Pull request by timelsass**
@dingo-d it looks like the testVersion config set in the wptrt ruleset.xml is overriding the cli --runtime-set for testVersion.  Removing the testVersion from the xml showed this to be true.  

Upon looking into the runner, it looks like it needs to be initialized first, and then set the set_config_data calls will work as expected.

### CODE REVIEW

File: src/api/class-template-tags-request.php [hunk 1]
```diff
@@ -56,25 +56,16 @@ private function get_template_tags() {
...
-				case 'Layout':
-					$template_tags['allowed_tags'] = $tags;
-					break;
-
-				default:
-					$template_tags['allowed_tags'] = array_merge( $template_tags['allowed_tags'], $tags );
-					break;
-			}
-		}
+		$template_tags = [
```
Comment (dingo-d) [inline src/api/class-template-tags-request.php]: Wow love how you replaced `foreach`. Usually I use `array_map` but I don't think I attempted to do that here because I had an array that had a key/value array type. This taught me something 🙂 

Can you just do a `return [ your code here ]` instead of assigning it to a variable and then returning the variable?

File: src/callback/class-run-sniffer-callback.php [hunk 2]
```diff
@@ -549,7 +532,25 @@ protected function get_sniff_results( ...$arguments ) {
 
 		$runner->init();
 
+		// Set default standard.
```
Comment (dingo-d) [inline src/callback/class-run-sniffer-callback.php]: I was going with this: https://gist.github.com/gsherwood/aafd2c16631a8a872f0c4a23916962ac as a suggestion for a runner. But if moving the config after the init works then it's ok by me :+1:

**Comment by dingo-d** [comment]
Thanks for the PR! I really appreciate it 🙂 

It's weird that the `testVersion` set in the ruleset meant for the plugin itself is picked up by the runner, as it should pick up the standard set in the config.

Anyhow, once you fix the minor thing I mentioned (just returning the array) the PR is good to merge 👍 

If you find any more issues or possible code optimisations feel free to send in a PR 🙂

File: src/api/class-template-tags-request.php (hunk 1 above)
Comment (timelsass) [reply src/api/class-template-tags-request.php]: I normally do that, but some people like keeping it assigned to a var for docblock parsing - wasn't sure if there was a preference, but I'm on the same page :slightly_smiling_face:

**Comment by dingo-d** [comment]
Thank you for the contribution! I really appreciate it. If you see some more things in the code that can be improved or fixed just send a PR 🙂
