### PR TITLE
move error into admin notice, fixes #165

### LINKED ISSUE #165: WordPress showing error while Theme Sniffer is activate.
I am getting an error when I open my local WordPress website while Theme Sniffer is activated!

**WordPress Version: WordPress 5.2 “Jaco”**
**Theme Sniffer: 1.0.0**

The site is experiencing technical difficulties. Please check your site admin email inbox for instructions.

`Fatal error: Uncaught Error: Class 'Theme_Sniffer\Api\Api_Response_Error' not found in /var/www/html/wp-content/plugins/theme-sniffer/src/api/class-template-tags-request.php:56 Stack trace: #0 /var/www/html/wp-content/plugins/theme-sniffer/src/api/class-template-tags-request.php(37): Theme_Sniffer\Api\Template_Tags_Request->get_template_tags() #1 /var/www/html/wp-includes/class-wp-hook.php(286): Theme_Sniffer\Api\Template_Tags_Request->check_template_tags('') #2 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #3 /var/www/html/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #4 /var/www/html/wp-settings.php(525): do_action('init') #5 /var/www/html/wp-config.php(107): require_once('/var/www/html/w...') #6 /var/www/html/wp-load.php(37): require_once('/var/www/html/w...') #7 /var/www/html/wp-admin/admin.php(34): require_once('/var/www/html/w...') #8 /var/www/html/wp-admin/index.php(10): require_once('/var/www/html/w...') #9 {main} thrown in /var/www/html/wp-content/plugins/theme-sniffer/src/api/class-template-tags-request.php on line 56`

Screenshot => https://ibb.co/3fqY3fC

Thank You

### PR DESCRIPTION
**Pull request by timelsass**

### CODE REVIEW

File: src/api/class-template-tags-request.php [hunk 1]
```diff
@@ -46,14 +44,16 @@ public function check_template_tags() {
...
-	 * @throws Api_Response_Error If API is down.
 	 * @return array Array of allowed template tags.
 	 */
 	private function get_template_tags() {
 		$tags_response = wp_remote_get( self::TEMPLATE_API_URL );
 
 		if ( is_wp_error( $tags_response ) ) {
-			throw Api_Response_Error::message( $tags_response->get_error_message() );
+			$this->error = $tags_response->get_error_message();
+			add_action( 'admin_notices', [ $this, 'notice' ] );
```
Comment (dingo-d) [inline src/api/class-template-tags-request.php]: Not sure why did you wrap this action in a method that is hooked to another action.

What I do is just hook to `admin_notices` and there I check for transients - if the transient is not `false` I add the error message from the transient to the error array and delete the transient, then just output the error notice out.

Comment (timelsass) [reply src/api/class-template-tags-request.php]: Generally speaking it's usually best to load and execute code only when it's needed, so that where the `load-toplevel_page_theme-sniffer` hook comes in - to run the transient check/update only on the theme-sniffer page where it's needed.  The same with `admin_notices` - there's no need for this to hook directly to that and run a check on the transient every page load.  

In https://github.com/WPTRT/theme-sniffer/issues/165 the user was encountering the error as soon as the plugin was activated because of the fatal.  We should try to minimize impact of those type of situations.  By executing only where (and importantly when) code is needed we reduce our footprint.  So taking this example - even _if_ we introduced a fatal in this particular situation - the user would only experience this scenario while specifically being on our theme-sniffer page, instead of the plugin rendering the whole wp-admin unusable, just our page is unusable.  

Performance wise - if we go directly to `admin_notices` -  the normal cache of data in the transient isn't a huge query or anything like that, but the call using `wp_remote_get` _can_ be expensive - something we don't need to happen outside of context of the actual sniff page itself.  Using the code that's there, we aren't caching the error for any period of time, so in the event the remote API is unreachable, or the data for whatever reason isn't correct coming back, _every_ page load is trying to make the remote fetch.  This can lag an admin area down pretty quickly, especially for calls with longer timeouts. We still want to hook into `admin_notices` to display the caught error, but there's not any reason we need this to be displayed site wide, just whenever we encounter the error.  It's sorta the same principal as when you enqueue your css/js - you only ever need to enqueue your scripts/styles on the pages where they are needed.  The alternative in this case would be we _can_ still hook into `admin_notices` directly, and to achieve the same result, we check $pagenow global to ensure it's on the page needed.

If you look at Query Monitor plugin in the hooks & actions section, you'll kinda see the behavior a little better, where `load-toplevel_page_theme-sniffer` is more or less the admin page specific `init`, and when there is no error, no hook is added by this plugin in `admin_notices`.  If we hook directly to `admin_notices` and force an error, then the hook is added, and only when on our page, instead of all pages.

Comment (dingo-d) [reply src/api/class-template-tags-request.php]: > Generally speaking it's usually best to load and execute code only when it's needed, so that's where the load-toplevel_page_theme-sniffer hook comes in - to run the transient check/update only on the theme-sniffer page where it's needed. The same with admin_notices - there's no need for this to hook directly to that and run a check on the transient every page load.

Yeah, I usually have a return early check in the callback, if I'm not on a specific screen - bail out 🙂

Thanks for the detailed explanation, seems totally reasonable to add it this way, I'll refactor my code so that it works like this 😄
